# WARNING - Generated by {fusen} from dev/flat_teaching.Rmd: do not edit by hand

#' Calculate Feed Conversion Ratio (FCR)
#'
#' This function calculates the Feed Conversion Ratio (FCR) based on average daily gain (ADG) and average daily feed intake (ADFI) results.
#' It also calculates a corrected FCR if stage information is available.
#'
#' @param adg_res A list containing ADG results, including 'adg_info' and 'adg_data' from adg_get().
#' @param adfi_res A list containing ADFI results, including 'adfi_info' and 'adfi_data' from adfi_get().
#'
#' @return A list containing:
#'   \item{fcr_res}{A data.table with FCR results, including 'fcr' and 'cor_fcr' (if applicable)}
#'   \item{adg_info}{The original ADG info data.table}
#'   \item{adg_data}{The original ADG data}
#'   \item{adfi_info}{The original ADFI info data.table}
#'   \item{adfi_data}{The original ADFI data}
#'
#' @note 
#' - This function assumes that 'adg_info' and 'adfi_info' are data.tables with columns 'responder' and 'location'.
#' - The function expects 'corrected_dfi' and 'lm_slope' columns in the joined data for FCR calculation.
#' - The corrected FCR calculation is only performed if a 'stage' column is present in the joined data.
#' - The variables 'min_weight_cut' and 'max_weight_cut' should be defined in the global environment or passed as parameters for the corrected FCR calculation.
#'
#' @export
#' @examples
#' nedap_csv_data <- mintyr::nedap
#' adg_results <- adg_get(data = nedap_csv_data)
#' adfi_results <- adfi_get(data = nedap_csv_data, adg_res = adg_results)
#' fcr_results <- fcr_get(adg_res = adg_results, adfi_res = adfi_results)
#' head(fcr_results$fcr_res)
#' head(fcr_results$fcr_summary)

# FCR results get
fcr_get <- function(adg_res, adfi_res) {
  
  # Parameter checks
  if (!is.list(adg_res) || !all(c("adg_info", "adg_data") %in% names(adg_res))) {
    stop("adg_res must be the output from adg_get() function")
  }
  if (!is.list(adfi_res) || !all(c("adfi_info", "adfi_data") %in% names(adfi_res))) {
    stop("adfi_res must be the output from adfi_get() function")
  }
  if (!data.table::is.data.table(adg_res$adg_info) || !data.table::is.data.table(adfi_res$adfi_info)) {
    stop("adg_info and adfi_info must be data.tables")
  }
  
  dt1 <- adg_res$adg_info
  dt2 <- adfi_res$adfi_info

  # Set keys for faster joining
  data.table::setkeyv(dt1, c("responder", "location"))
  data.table::setkeyv(dt2, c("responder", "location"))

  # Join the data tables
  joined_dt <- dt1[dt2, nomatch = 0]

  # Calculate FCR
  joined_dt[, fcr := corrected_dfi / lm_slope]

  # Check if 'stage' column exists
  if ("stage" %in% colnames(joined_dt)) {
    # Parse stage values
    stage_values <- as.numeric(unlist(strsplit(unique(joined_dt$stage), "-")))

    # Calculate corrected FCR
    joined_dt[, cor_fcr := fcr +
                (stage_values[1] - min_weight_cut/1000) * 0.005 +
                (stage_values[2] - max_weight_cut/1000) * 0.005]
  }
  
  fcr_results_stats <- fcr_summary(joined_dt)
  
  # Create a new list with all results
  result_list <- list(
    fcr_res = joined_dt,
    adg_info = dt1,
    adg_data = adg_res$adg_data,
    adfi_info = dt2,
    adfi_data = adfi_res$adfi_data,
    fcr_summary = fcr_results_stats
  )

  return(result_list)
}
# Helper function to process data
process_fcr_data <- function(data) {
  # Determine column names
  if ("min_weight_cut" %in% names(data)) {
    weight_cols <- c("min_weight_cut", "max_weight_cut")  # If "min_weight_cut" is a column, set weight columns
  } else if ("min_weight_origin" %in% names(data)) {
    weight_cols <- c("min_weight_origin", "max_weight_origin")  # If "min_weight_origin" is a column, set weight columns
  } else {
    stop("Unknown data format")  # If neither column exists, stop execution with an error message
  }

  common_cols <- c("lm_slope", "test_days", "origin_dfi", "corrected_dfi", "fcr")  # Define common columns

  if ("cor_fcr" %in% names(data)) {
    common_cols <- c(common_cols, "cor_fcr")  # Add "cor_fcr" to common columns if it exists
  }

  # Combine all selected columns
  selected_cols <- c(weight_cols, common_cols)

  # Perform operations on these columns in data
  data <- data[, ..selected_cols]  # Select only the chosen columns from the data

  # Find all columns that contain "weight"
  weight_cols <- grep("weight", names(data), value = TRUE)

  # Divide all values in these columns by 1000
  data[, (weight_cols) := lapply(.SD, function(x) x / 1000), .SDcols = weight_cols]

  return(data)  # Return the processed data
}
# Helper function to calculate statistics
fcr_data_stats <- function(data) {
  # Calculate statistics for each column in the data
  stats <- data[, lapply(.SD, function(x) {
    list(
      N = sum(!is.na(x)),  # Number of non-NA values
      min = min(x, na.rm = TRUE),  # Minimum value, ignoring NA
      max = max(x, na.rm = TRUE),  # Maximum value, ignoring NA
      median = stats::median(x, na.rm = TRUE),  # Median value, ignoring NA
      mean = mean(x, na.rm = TRUE),  # Mean value, ignoring NA
      sd = stats::sd(x, na.rm = TRUE),  # Standard deviation, ignoring NA
      cv = stats::sd(x, na.rm = TRUE) / mean(x, na.rm = TRUE)  # Coefficient of variation (CV)
    )
  })]

  return(stats)  # Return the calculated statistics
}
# FCR results summary
fcr_summary <- function(data) {

  # Check if all required columns are present
  weight_cols <- c("min_weight_cut", "max_weight_cut", "min_weight_origin", "max_weight_origin")
  common_cols <- c("lm_slope", "test_days", "origin_dfi", "corrected_dfi", "fcr", "cor_fcr")

  if (any(weight_cols %in% names(data))) {
    required_cols <- c(common_cols, weight_cols)
  } else {
    stop("The 'data' argument is missing required weight columns")
  }

  missing_cols <- setdiff(required_cols, names(data))

  # Process data and calculate statistics
  fcr_stats <- process_fcr_data(data) |>
    fcr_data_stats()

  fcr_summary_data <- data.table::data.table(t(fcr_stats))

  data.table::setnames(fcr_summary_data, c("N", "min", "max", "median", "mean", "sd", "cv"))

  fcr_summary_data$traits <- colnames(fcr_stats)

  data.table::setcolorder(fcr_summary_data, c("traits", setdiff(names(fcr_summary_data), "traits")))

  num_cols <- c("N", "min", "max", "median", "mean", "sd", "cv")
  fcr_summary_data[, (num_cols) := lapply(.SD, function(x) as.numeric(unlist(x))), .SDcols = num_cols]


  fcr_summary_data[, cv := sprintf("%.2f%%", round(cv * 100, 2))][, N := as.character(N)]

  numeric_cols <- names(fcr_summary_data)[sapply(fcr_summary_data, is.numeric)]
  fcr_summary_data[, (numeric_cols) := lapply(.SD, function(x) sprintf("%0.2f", as.numeric(x))), .SDcols = numeric_cols][]

  return(fcr_summary_data)
}
