# WARNING - Generated by {fusen} from /dev/flat_teaching.Rmd: do not edit by hand

#' FCR summary of nedap pig performance station
#'
#' @param data A data.frame or a data.table. The data should include at least one pair of weight columns ("min_weight_cut" and "max_weight_cut" or "min_weight_origin" and "max_weight_origin") and the following common columns: "lm_slope", "test_days", "origin_dfi", "corrected_dfi", "fcr". The column "cor_fcr" is optional.
#'
#' @return A data.frame that includes the statistics of each column.
#'
#' @export

#' @examples
#' data <- rio::import("C:/Users/Dell/Downloads/ppt_test_data.xlsx")
#' fcr_res <- fcr_get(data = data, my_break = c(30, 100))
#' fcr_summary(fcr_res[[1]])
fcr_summary <- function(data) {
  selected_cols <- NULL
  
  # Argument checks
  # Check if the input data is either a data.frame or a data.table
  if (!inherits(data, "data.frame") && !inherits(data, "data.table")) {
    stop("The 'data' argument must be a data.frame or a data.table")
  }

  # Check if all required columns are present
  weight_cols <- c("min_weight_cut", "max_weight_cut", "min_weight_origin", "max_weight_origin")
  common_cols <- c("lm_slope", "test_days", "origin_dfi", "corrected_dfi", "fcr", "cor_fcr")

  if (any(weight_cols %in% names(data))) {
    required_cols <- c(common_cols, weight_cols)
  } else {
    stop("The 'data' argument is missing required weight columns")
  }

  missing_cols <- setdiff(required_cols, names(data))

  # Helper function to process data
  process_data <- function(data) {
    # Determine column names
    if ("min_weight_cut" %in% names(data)) {
      weight_cols <- c("min_weight_cut", "max_weight_cut")
    } else if ("min_weight_origin" %in% names(data)) {
      weight_cols <- c("min_weight_origin", "max_weight_origin")
    } else {
      stop("Unknown data format")
    }

    common_cols <- c("lm_slope", "test_days", "origin_dfi", "corrected_dfi", "fcr")

    if ("cor_fcr" %in% names(data)) {
      common_cols <- c(common_cols, "cor_fcr")
    }

    # Combine all selected columns
    selected_cols <- c(weight_cols, common_cols)

    # # Perform operations on these columns in data
    # data <- data[, ..selected_cols]
    # 
    # # Find all columns that contain "weight"
    # weight_cols <- grep("weight", names(data), value = TRUE)
    # 
    # # Divide all values in these columns by 1000
    # data[, (weight_cols) := lapply(.SD, function(x) x / 1000), .SDcols = weight_cols][]
    
    data <- data |>
      dplyr::select(dplyr::all_of(selected_cols)) |>
      dplyr::mutate(dplyr::across(dplyr::all_of(dplyr::contains("weight")), function(x) x / 1000))
    
    return(data)
  }

  # Helper function to calculate statistics
  data_stats <- function(data) {
    # Convert data.table to data.frame
    data <- as.data.frame(data)

    data |>
      dplyr::summarise(dplyr::across(dplyr::everything(),
                                     list(N = ~ sum(!is.na(.x)),
                                          min = min,
                                          max = max,
                                          median = ~stats::median(.x, na.rm = TRUE),
                                          mean = ~mean(.x, na.rm = TRUE),
                                          sd = ~stats::sd(.x, na.rm = TRUE),
                                          cv = ~stats::sd(.x, na.rm = TRUE) / mean(.x, na.rm = TRUE)))) |>
      dplyr::ungroup() |>
      dplyr::mutate(dplyr::across(dplyr::where(is.numeric), round, 4)) |>
      dplyr::mutate(dplyr::across(dplyr::matches("(_mean|_sd|_min|_max|_median)$"), ~sprintf("%0.2f", .x))) |>
      dplyr::mutate(dplyr::across(dplyr::matches("_cv$"), ~sprintf("%0.4f", .x))) |>
      dplyr::mutate_at(dplyr::vars(dplyr::ends_with("_cv")), as.numeric) |>
      dplyr::mutate_at(dplyr::vars(dplyr::ends_with("_cv")), scales::percent, accuracy = 0.01) |>
      tidyr::pivot_longer(dplyr::everything(), names_to = c("set", ".value"),names_pattern = "(.+|._.+)_(.+)") |>
      tidyr::unite("mean+/-sd",mean:sd, sep = "+/-")
  }

  # Process data and calculate statistics
  processed_data <- process_data(data)
  result <- data_stats(processed_data)

  return(result)
}
