# WARNING - Generated by {fusen} from /dev/flat_teaching.Rmd: do not edit by hand

#' Import CSV files using specified R packages
#'
#' @param file_list A list of file paths to CSV files
#' @param package Package to use for reading CSV. Options are "data.table", "vroom", or "readr". Default is "data.table"
#' @param ... Additional arguments to pass to the read function
#' @return A combined data.frame/data.table of all input CSV files
#' @export

#' @examples
#' list_csv <- list.files("C:/Users/Dell/Downloads/location301", pattern = ".csv", full.names = TRUE)
#' data <- import_csv(list_csv)
import_csv <- function (file_list, package = "data.table", ...) {
  # Argument check
  if (!is.character(file_list) || !all(file.exists(file_list))) { # 检查file_list是否为字符向量并且所有的文件都存在
    stop("file_list must be a vector of existing file paths.")    # 如果检查失败，停止并返回错误消息
  }

  if (!is.character(package) || !package %in% c("data.table", "vroom", "readr")) { # 检查package参数是否为字符且属于指定的几个包之一
    stop("package must be one of 'data.table', 'vroom', 'readr'.") # 如果检查失败，停止并返回错误消息
  }

  # Load package
  if(!require(package, character.only = TRUE)) { # 尝试加载指定的包，如果加载失败，停止并返回错误消息
    stop(paste0("Package '", package, "' could not be loaded. Please install it."))
  }

  switch(package, # 根据package参数选择执行哪个分支的代码
         "data.table" = { # 如果package为"data.table"，执行以下代码
           data.table::rbindlist(purrr::map(file_list, function(x,
                                                                ...) {
             data.table::fread(x, ...)
           }, ...))
           # 使用purrr的map函数对file_list中的每个文件应用fread函数，然后使用rbindlist函数将结果合并为一个data.table
         },
         "vroom" = { # 如果package为"vroom"，执行以下代码
           vroom::vroom(file_list, ...) # 使用vroom函数直接读取file_list中的所有文件
         },
         "readr" = { # 如果package为"readr"，执行以下代码
           purrr::map_dfr(file_list, function(x, ...) {
             readr::read_csv(x, ...)
           }, ...)
           # 使用purrr的map_dfr函数对file_list中的每个文件应用read_csv函数，将结果合并为一个data.frame
         },
         stop("Invalid package specified.") # 如果package不属于以上任何一个，停止并返回错误消息
  )
}
